package com.example.taskmate.data.model

/**
 * Task.kt
 * Location: data/model/Task.kt
 *
 * Represents a single study task (to-do item).
 *
 * Firestore path:
 *   users/{userId}/tasks/{taskId}
 *
 * The tasks are stored as a subcollection under each user document.
 * This means each user only ever reads their own tasks — no
 * security rules needed beyond checking userId == auth.uid.
 *
 * Task priority levels:
 *   0 = Low    (gray tag)
 *   1 = Medium (amber tag)
 *   2 = High   (red tag)
 */
data class Task(

    // Firestore document ID — set after document is created
    // Pattern: auto-generated by Firestore, stored back into the document
    val id: String = "",

    // Firebase Auth UID of the owner
    // Used to verify ownership in Firestore security rules
    val userId: String = "",

    // Task description entered by the user
    // Example: "Solve 20 integration problems"
    val title: String = "",

    // Optional longer description
    val description: String = "",

    // Subject this task belongs to
    // Links to a Subject document by its Firestore document ID
    val subjectId: String = "",

    // Subject name stored here for display without a second Firestore lookup
    // Example: "Mathematics"
    val subjectName: String = "",

    // Hex color of the subject — used for the subject tag pill background
    // Example: "#7059D0" for Mathematics (purple)
    val subjectColorHex: String = "#7059D0",

    // Due date as Unix timestamp (milliseconds)
    // 0L means no due date set
    val dueDate: Long = 0L,

    // Whether the task has been completed
    // Toggled by the checkbox in item_task.xml
    val completed: Boolean = false,

    // Unix timestamp when the task was marked complete
    // 0L if not yet completed
    val completedAt: Long = 0L,

    // Priority: 0 = Low, 1 = Medium, 2 = High
    val priority: Int = 0,

    // Unix timestamp when the task was created
    val createdAt: Long = System.currentTimeMillis()

) {
    // ── Computed properties (NOT stored in Firestore) ──────────────────

    /**
     * Returns true if the task has a due date set.
     */
    val hasDueDate: Boolean
        get() = dueDate > 0L

    /**
     * Returns true if the task is overdue:
     *   - Has a due date
     *   - Due date is in the past
     *   - Task is not yet completed
     */
    val isOverdue: Boolean
        get() = hasDueDate &&
                dueDate < System.currentTimeMillis() &&
                !completed

    /**
     * Returns the priority as a readable label.
     * Used for accessibility and display in dialogs.
     */
    val priorityLabel: String
        get() = when (priority) {
            0    -> "Low"
            1    -> "Medium"
            2    -> "High"
            else -> "Low"
        }

    /**
     * Returns true if this task is due today.
     * Compares only the date portion, ignoring time.
     */
    val isDueToday: Boolean
        get() {
            if (!hasDueDate) return false
            val taskCal = java.util.Calendar.getInstance().apply {
                timeInMillis = dueDate
            }
            val todayCal = java.util.Calendar.getInstance()
            return taskCal.get(java.util.Calendar.YEAR) == todayCal.get(java.util.Calendar.YEAR) &&
                    taskCal.get(java.util.Calendar.DAY_OF_YEAR) == todayCal.get(java.util.Calendar.DAY_OF_YEAR)
        }

    companion object {
        // Priority constants — use these instead of raw integers
        const val PRIORITY_LOW    = 0
        const val PRIORITY_MEDIUM = 1
        const val PRIORITY_HIGH   = 2
    }
}